### ISSUE TITLE
Enter keyboard event to submit current editing math

### ISSUE THREAD

**Issue by phillipngn** [ibastawisi/matheditor#3]
Hi @ibastawisi , I spent a couple of days to read this repo. I would like to ask you on how I can listen to the Enter event while creating a math equation then submit it and exit from creating mode (like continue to enter normal text).
Many thanks!

**Comment by phillipngn** [comment]
I think first I can listen to the `insertLineBreak` in the `input` event and then add a handler to set the selection range position after of the current node.

**Comment by ibastawisi** [comment]
> I think first I can listen to the `insertLineBreak` in the `input` event and then add a handler to set the selection range position after of the current node.

yeah that would do it..
``` typescript
if (event.inputType === "insertLineBreak") {
  event.stopPropagation();
  editor.update(() => {
    const parentRootElement = editor.getRootElement();
    if (parentRootElement !== null) {
      parentRootElement.focus();
    }
    const node = $getNodeByKey(nodeKey);
    if (!$isMathNode(node)) return;
    node.selectNext().insertParagraph();
  });
}
```
inserting a paragraph will add a newline after the current line.

**Comment by ibastawisi** [comment]
by the way, the developer of mathlive is working on newline feature.
https://github.com/arnog/mathlive/commit/5bbbf43ec2e09e4ddcd5f1cdca57beee284d79ab
I plan to handle newline insertion after next mathlive release.

**Comment by phillipngn** [comment]
@ibastawisi awesome, can't wait to see that
