### ISSUE TITLE
Problems when inputing Latex after auto-\text

### ISSUE THREAD

**Issue by chardetm** [ibastawisi/matheditor#4]
Hello @ibastawisi,

I think I found a bug when inputing maths.

**Steps to reproduce:**

- create a math node
- with keyboard, type "let" (without quotes) - it is automatically transformed to \text{let}
- open LaTeX window and change the LaTeX source to "\text{let} x"
- confirm

After this, the Lexical node display is broken, but the data itself (in the Lexical tree) is still valid. However changing it with the keyboard breaks it.

**Comment by ibastawisi** [comment]
I couldn't reproduce the issue on my end. Please have a look at mathlive docs on smart-mode
https://cortexjs.io/docs/mathlive/#(MathfieldElementAttributes%3Ainterface).smart-mode

You need a math operator to exit text mode automatically
<html>
<body>


“if x” | all in text mode, maybe the next word is xylophone?
-- | --
“if x >” | “if” stays in text mode, but now “x >” is in math mode


</body>
</html>

**Comment by chardetm** [comment]
The problem is not the way to get out of that mode, the problem is that the math node becomes broken after a given set of operations. Please find attached a video of me performing the steps mentioned in my first message and showing the problem occurring. 

https://github.com/ibastawisi/matheditor/assets/15015176/816acc3d-7cd9-4939-b14f-3e8ae06399b6

**Comment by ibastawisi** [comment]
oh I got it, thanks.
I think I should programmatically switch to math mode, I'll take a look on it ASAP.
