### ISSUE TITLE
There is something wrong with the formula style in the tutorial

### ISSUE THREAD

**Issue by panhezeng** [ibastawisi/matheditor#5]
![image](https://github.com/ibastawisi/matheditor/assets/354878/ba831ed1-6d49-475e-ac90-733f720b6396)

The line above the equals symbol is too faint.

**Comment by panhezeng** [comment]
The screenshots look fine, but when they go online on the web page, they look blurry.

**Comment by panhezeng** [comment]
![image](https://github.com/ibastawisi/matheditor/assets/354878/bfcfca1b-bdbb-4c1b-bdb0-5403d330bda7)

**Comment by ibastawisi** [comment]
sorry but I can't do anything about that!
