### ISSUE TITLE
Add `data-gutter` on exporting `CodeNode`

### ISSUE THREAD

**Issue by 2wheeh** [ibastawisi/matheditor#6]
Hi ! I came here to want to follow this : https://github.com/facebook/lexical/pull/4743#issuecomment-1876692195

 I found a way to set `data-gutter` without implementing a whole custom node:
-  https://github.com/facebook/lexical/pull/4254

It can be easier with this feature like this
```ts
   html: {
      export: new Map([
        [
          CodeNode,
          (_, node) => {
            const element = document.createElement('pre');
            element.setAttribute('spellcheck', 'false');
            const language = node.getLanguage();

            if (language) {
              element.setAttribute('data-highlight-language', language);
            }

            const children = node.getChildren();
            const childrenLength = children.length;

            let gutter = '1';
            let count = 1;
            for (let i = 0; i < childrenLength; i++) {
              if ($isLineBreakNode(children[i])) {
                gutter += '\n' + ++count;
              }
            }

            element.setAttribute('data-gutter', gutter);

            return { element };
          },
        ],
      ]),
    },
```

**Comment by ibastawisi** [comment]
looks good to me!
by the way, why is this issue here and not on https://github.com/facebook/lexical?

**Comment by 2wheeh** [comment]
@ibastawisi I just tried to find in which codebase you implement that and thought it is here. hope you don't mind it.

**Comment by ibastawisi** [comment]
> @ibastawisi I just tried to find in which codebase you implement that and thought it is here. hope you don't mind it.

yeah no problem.
this editor config thing never worked for me!
I also needed to add syntax highlighting for c sharp, so I ended up copying the sources for the node and doing what I wanted.

**Comment by 2wheeh** [comment]
btw for more language support, you just have to import prismjs sub package:
```ts
import 'prismjs/components/prism-csharp'
```
- https://github.com/facebook/lexical/discussions/2176

**Comment by ibastawisi** [comment]
> btw for more language support, you just have to import prismjs sub package:
> 
> ```ts
> import 'prismjs/components/prism-csharp'
> ```
> 
> * [Adding new language for code highlighting facebook/lexical#2176](https://github.com/facebook/lexical/discussions/2176)

yeah that's what I did, thanks a lot.
