### ISSUE TITLE
Writing direction in bullet/numbered lists doesn't persist when sharing document in view mode

### ISSUE THREAD

**Issue by Creative-Geek** [ibastawisi/matheditor#7]
### When sharing a document in view mode, the writing direction of text in any lists always appears from left to right.

Here is an example document in edit mode:

![image](https://github.com/ibastawisi/matheditor/assets/20252333/fab97475-9186-4679-934b-239233e523da)

Here's the same document when shared in view mode:

![image](https://github.com/ibastawisi/matheditor/assets/20252333/f649d9cf-bd02-49b2-85c9-0ea440480f94)

Notice that the paragraph with the bullet point becomes unreadable in view mode.

**Comment by ibastawisi** [comment]
oh.. I'll take a look.
it seems that text direction isn't properly preserved for server-side rendering.

**Comment by ibastawisi** [comment]
it seems that I have an open pull request regarding this issue but it didn't get merged :(
https://github.com/facebook/lexical/pull/4942

For now I copied the code with the fix, hopefully I can get the lexical team to merge it so I'd revert this mess :)
https://github.com/ibastawisi/matheditor/commit/a7a1301
