### ISSUE TITLE
The Dark/Light Theme toggle button has disappeared 

### ISSUE THREAD

**Issue by potaatu** [ibastawisi/matheditor#9]
I switched from dark mode to light mode after a long time using the app, and once I did, fo rsone reason, the toggle button for changing between dark and light mode vanished. I had to clear my entire browser data to bring back dark mode in the app, however, the toggle button is still missing, and I'm unable to switch between the two manually, unless I turn off datk mode completely from my phone settings.

**Comment by ibastawisi** [comment]
I decided to get rid of the toggle and follow system color scheme, I think it's better that way.
convince me otherwise and I will revert it.

**Comment by potaatu** [comment]
Ahh, so that's what it is.
If it's an intended change, I guess I don't have much to say about it, however, since you've given me the chance, I might as well try 😂

I'm always in Dark mode system-wide, and I also use the app in dark mode for the most part. However, when I'm including any sketched from Excalidraw, the printed images always appear with white background, and there seems no way to change that behaviour. And while in dark mode, the sketches just don't blend with the rest of the document. So if I'm just about to take a little screenshot or something, I quickly switch to the light mode and take it. Makes it much easier to switch to light mode for the rest of the UI. Also, it just feels better to write stuff on a white background, but I don't want to use light mode for the rest of my system either. So...
yeah, I guess it helps me kinda lot sometimes?

**Comment by ibastawisi** [comment]
Ok I should've changed the local storage key to ignore the previous user preference, that one is on me, sorry for that.
Would it be better if Sketches background are removed?
I removed the toggle to simplify the code and avoid inconsistencies between server-rendered color scheme and user preferred 
color scheme.

**Comment by potaatu** [comment]
Yeah, that should help too (removing the background), as long as it doesn't cause weird rendering issues to the sketch strokes! 😂
Not having to switch to light mode just for the sketches would be a big plus.

**Comment by ibastawisi** [comment]
I'll see what I can do.

**Comment by potaatu** [comment]
Looking forward to it
